MODULE CONT_CC
USE SGLOBAL, ONLY : NELEE, NCONEE, LLEE, NSEE, NSEDEE, NLFEE
IMPLICIT NONE
!*------------------------------ Start of CONT.CC ----------------------*
!*
!*                       INCLUDE FILE FOR CONTAMIANT VARIABLES AND DATA
!*
!*----------------------------------------------------------------------*
!* Version:  SHETRAN/INCLUDE/CONT.CC/4.1
!* Modifications:
!*                           JE     26/4/91   3.1     WRITTEN
!*                           JE     13/6/91   3.1     COMPLETED
!*                           JE     18/6/91   3.1     BLOCK WELC ADDED
!* RAH  970224  4.1  Explicit typing.
!  JE  NOV 04 ---- Convert to FORTRAN 95
!*----------------------------------------------------------------------*
!* Imported constants
!*                      LLEE,NCONEE,NELEE,NLFEE,NSEE
!* Commons
      DOUBLEPRECISION CCAPB(NELEE,NCONEE),CCPBO(NELEE,NCONEE)
      DOUBLEPRECISION CCAPE(NELEE,NCONEE)
      DOUBLEPRECISION CCAPI(NCONEE),      CCAPIO(NCONEE)
      DOUBLEPRECISION CCAPR(NELEE,NCONEE),CCAPRO(NELEE,NCONEE)
      DOUBLEPRECISION IIICF(NCONEE),      IIICFO(NCONEE)
!      COMMON/  CBDY   /CCAPB,CCPBO,CCAPE,CCAPI,CCAPIO,CCAPR,CCAPRO,
!     $                 IIICF,IIICFO
!*                             CONTAMINANT CONCENTRATION AND
!*                             FLUX BOUNDARY CONDITIONS

      DOUBLEPRECISION CCCCW(NELEE,NCONEE)
!      COMMON/  WELC   /CCCCW
!*                             CONTAMINANT CONCENTRATION IN WELL WATER

      DOUBLEPRECISION CCCC(NELEE,LLEE,NCONEE),CCCCO(NELEE,LLEE,NCONEE)
      DOUBLEPRECISION SSSS(NELEE,LLEE,NCONEE),SSSSO(NELEE,LLEE,NCONEE)
!      COMMON/  CONC   /CCCC,CCCCO,SSSS,SSSSO
!*                             CONCENTRATIONS WITHIN CATCHMENT

      DOUBLEPRECISION GCPLA(NCONEE),GGLMSO(NCONEE)
!      COMMON/  GEN    /GCPLA,GGLMSO
!*                             CONTAMINANT DECAY RATES

      DOUBLEPRECISION CCAPIN(NCONEE)
!      COMMON/  INIT   /CCAPIN
!*                             INITIAL CONCENTRATION

      DOUBLEPRECISION ALPHA(NSEE,NCONEE),FADS(NSEE,NCONEE),GNN(NCONEE)
      DOUBLEPRECISION KDDLS(NSEDEE,NCONEE),KDDSOL(NSEE,NCONEE)
!      COMMON/  NNNN   /ALPHA,FADS,GNN,KDDLS,KDDSOL
!*                             CONTAMINANT PROPERTIES FOR SOIL
!*                             AND SEDIMENT

      INTEGER          NCON
!      COMMON/  NCONS  /NCON
!*                             NUMBER OF CONTAMINANTS

      DOUBLEPRECISION FCPBKO(NLFEE,2,LLEE,NCONEE)
      DOUBLEPRECISION GCPBKO(NLFEE,2,LLEE,NCONEE)
      DOUBLEPRECISION    FSF(NLFEE,NCONEE),       FSFC(NLFEE,NCONEE)
      DOUBLEPRECISION   FSFT(NLFEE,NCONEE),        RSW(NELEE,NCONEE)
      DOUBLEPRECISION   RSWC(NELEE,NCONEE),       RSWT(NELEE,NCONEE)
!      COMMON/  RETN   /FCPBKO,GCPBKO,FSF,FSFC,FSFT,RSW,RSWC,RSWT
!*                             RETARDATION VARIABLES USED IN THE
!*                             CALCULATIONS FOR IMPLICIT LATERAL
!*                             COUPLING BY BANK EROSION AND WITH
!*                             CONVECTION WITH SURFACE FLOWS

      DOUBLEPRECISION ALPHBD(NCONEE),ALPHBS(NCONEE)
!      COMMON/  SBED   /ALPHBD,ALPHBS
!*                             COEFFICIENTS FOR EXCHANGE BETWEEN CELLS
!*                             OF A LINK

!PRIVATE :: NELEE, NCONEE, LLEE, NSEE, NSEDEE, NLFEE
END MODULE CONT_CC