!MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MODULE VISUALISATION_EXTRAS
IMPLICIT NONE

INTEGER, DIMENSION(:), POINTER               :: acol
DOUBLE PRECISION, DIMENSION(:,:,:), POINTER  :: vpsed
!DEC$ ATTRIBUTES DLLEXPORT :: acol, vpsed

PRIVATE
PUBLIC :: REACT, acol, vpsed

CONTAINS

!SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SUBROUTINE react(p, j)
!DEC$ ATTRIBUTES DLLEXPORT :: react
INTEGER, INTENT(IN)           :: p
INTEGER, INTENT(IN), OPTIONAL :: j
INTEGER                       :: n
IF(PRESENT(j)) THEN
    ALLOCATE(acol(p), vpsed(j,2,p))    
ELSE
    n = SIZE(acol)
    IF(p>n) THEN
        n = MAX(1,n/10)
        CALL INCREMENT_I1(acol, n)
        CALL INCREMENT_D3(vpsed, n)
    ENDIF
ENDIF
END SUBROUTINE react

!SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SUBROUTINE increment_I1(s,n)
INTEGER, DIMENSION(:), POINTER :: s,old=>NULL()
INTEGER, INTENT(IN)            :: n
INTEGER                        :: sz
IF(ASSOCIATED(s)) THEN ; sz=SIZE(s) ; old=>s ; NULLIFY(s) ; ELSE ; sz=0 ; ENDIF
ALLOCATE(s(sz+n))
IF(sz>0) THEN ; s(1:sz)=old ; DEALLOCATE(old) ; ENDIF
END SUBROUTINE increment_I1

!SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SUBROUTINE increment_D3(s,n)
DOUBLE PRECISION, DIMENSION(:,:,:), POINTER :: s,old=>NULL()
INTEGER, INTENT(IN)                         :: n
INTEGER                                     :: sh(3)
sh=SHAPE(s)
old=>s
NULLIFY(s)
ALLOCATE(s(sh(1),sh(2),sh(3)+n))
s(:,:,1:sh(3))=old
DEALLOCATE(old)
END SUBROUTINE increment_D3

END MODULE VISUALISATION_EXTRAS
